#!/bin/bash
people=`\ls keys | sed 's/keys\///
    s/_.*//' | sort -u`
sizes=`\ls keys | sed 's/.*_//
    s/\..*//' | sort -un`
for size in $sizes; do
    for per1 in $people; do
        start=0
        for per2 in $people; do
            if [ $per1 == $per2 ]; then
                start=1
            elif [ $start == 1 ]; then
                priv1=keys/${per1}_${size}.priv
                priv2=keys/${per2}_${size}.priv
                pub1=keys/${per1}_${size}.pub
                pub2=keys/${per2}_${size}.pub
                if [ -e $priv1 -a -e $priv2 -a -e $pub1 -a -e $pub2 ]; then
                    key1=`secret $priv1 $pub2`
                    key2=`secret $priv2 $pub1`
                    key2=`secret $priv2 $pub1`
                    if [ $key1 != $key2 ]; then
                        echo "Failed for $privKey and $pubKey"
                        exit 1
                    fi
                    echo "Passed ${per1}_${size} and ${per2}_${size}"
                    echo $key1
                fi
            fi
        done
    done
done
