#!/bin/bash
people="alice bob eve"
for guy1 in $people; do
    for guy2 in $people; do
        key1=`secret keys/${guy1}_127.priv keys/${guy2}_127.pub`
        key2=`secret keys/${guy2}_127.priv keys/${guy1}_127.pub`
        echo $key1
        echo $key2
        if [ $key1 != $key2 ]; then
            echo "Failed for $guy1 and $guy2"
            exit 1
        fi
        echo "Passed $guy1 $guy2 for 127"
        key1=`secret keys/${guy1}_521.priv keys/${guy2}_521.pub`
        key2=`secret keys/${guy2}_521.priv keys/${guy1}_521.pub`
        echo $key1
        echo $key2
        if [ $key1 != $key2 ]; then
            echo "Failed for $guy1 and $guy2"
            exit 1
        fi
        echo "Passed $guy1 $guy2 for 521"
    done
done
